### ISSUE TITLE
praw.errors.APIException: (DELETED_COMMENT) `that comment has been deleted` on field `parent`

### ISSUE THREAD

**Issue by tek0011** [tek0011/RedditInfoBot#7] opened 2015-04-09 13:19 UTC
Not sure what happened here.  The comment never got deleted.  

http://i.imgur.com/Ymp6RNb.png

**Comment by jacobstein123** [comment] 2015-05-05 04:40
Is this the same as Issue #17

**Comment by tek0011** [comment] 2015-05-10 13:34
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 363, in <module>
    find_username_mentions()
  File "info_bot_nsfw.py", line 221, in find_username_mentions
    give_more_info(comment)
  File "info_bot_nsfw.py", line 163, in give_more_info
    comment.reply(reply)
  File "C:\Python27\lib\site-packages\praw\objects.py", line 384, in reply
    response = self.reddit_session._add_comment(self.fullname, text)
  File "C:\Python27\lib\site-packages\praw\decorators.py", line 338, in wrapped
    return function(cls, *args, **kwargs)
  File "C:\Python27\lib\site-packages\praw\__init__.py", line 2173, in _add_comment
    retry_on_error=False)
  File "C:\Python27\lib\site-packages\praw\decorators.py", line 189, in wrapped
    raise error_list[0]
praw.errors.APIException: (DELETED_COMMENT) `that comment has been deleted` on field `parent`

**Comment by tek0011** [comment] 2015-05-12 11:08
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 414, in <module>
    find_username_mentions()
  File "info_bot_nsfw.py", line 271, in find_username_mentions
    give_more_info(comment)
  File "info_bot_nsfw.py", line 213, in give_more_info
    comment.reply(reply)
  File "C:\Python27\lib\site-packages\praw\objects.py", line 384, in reply
    response = self.reddit_session._add_comment(self.fullname, text)
  File "C:\Python27\lib\site-packages\praw\decorators.py", line 338, in wrapped
    return function(cls, *args, **kwargs)
  File "C:\Python27\lib\site-packages\praw\__init__.py", line 2173, in _add_comment
    retry_on_error=False)
  File "C:\Python27\lib\site-packages\praw\decorators.py", line 189, in wrapped
    raise error_list[0]
praw.errors.APIException: (DELETED_COMMENT) `that comment has been deleted` on field `parent`

**Comment by jacobstein123** [comment] 2015-05-13 02:19
I edited the comment_exists function to see if that will help, but I'm leaving this issue open for now.

**Comment by jacobstein123** [comment] 2015-06-18 02:56
Duplicate of Issue #30

**Closed by jacobstein123** 2015-06-18 02:56 UTC
Labels: bug
